title: "let's get good together"
description: "let's get good together"
author:
  name: "ahmet.ak"
  email: "ahmeetaak@gmail.com"

baseurl: /myblog

markdown: GFM

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "ahmet.ak"
year : "2022"

google_analytics: G-XK8LW2PQWZ
